[package]
name = "cargo-pretty-build"
description = "A cargo build wrapper with a live, animated status view"
repository = "https://github.com/romancitodev/cargo-pretty-build"
authors = ["romancitodev"]
license = "MIT"
version = "0.1.1"
edition = "2024"

[dependencies]
cargo_metadata = "0.19"
colorgrad = "0.8"
crossterm = "0.29"
eyre = "0.6"
serde_json = "1"
nobubbles = { version = "0.1.1", features = ["gradient"] }
